2025-08-13T22:02:45: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:45.879Z'
}
2025-08-13T22:02:46: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:46.964Z'
}
2025-08-13T22:02:49: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:49.062Z'
}
2025-08-13T22:17:03: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:03.545Z'
}
2025-08-13T22:17:04: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:04.624Z'
}
2025-08-13T22:17:06: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:06.703Z'
}
2025-08-13T22:17:33: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:33.723Z'
}
2025-08-13T22:17:34: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:34.802Z'
}
2025-08-13T22:17:36: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:36.883Z'
}
2025-08-13T22:26:27: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:27.068Z'
}
2025-08-13T22:26:28: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:28.143Z'
}
2025-08-13T22:26:30: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:30.063Z'
}
2025-08-13T22:26:30: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:30.214Z'
}
2025-08-13T22:26:31: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:31.643Z'
}
2025-08-13T22:26:33: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:33.724Z'
}
2025-08-13T22:26:37: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:37.333Z'
}
2025-08-13T22:26:38: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:38.415Z'
}
2025-08-13T22:26:40: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:40.504Z'
}
2025-08-13T22:26:48: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:48.503Z'
}
2025-08-13T22:26:49: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:49.573Z'
}
2025-08-13T22:26:51: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:51.649Z'
}
2025-08-13T22:28:12: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:12.907Z'
}
2025-08-13T22:28:14: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:14.071Z'
}
2025-08-13T22:28:16: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:16.170Z'
}
2025-08-13T23:57:54: JWT verification failed: jwt malformed
2025-08-14T00:01:05: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:318:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:182:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:01:26: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:318:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:182:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:10:59: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:12:52: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:12:58: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:12:58.213Z'
}
2025-08-14T00:12:59: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:12:59.282Z'
}
2025-08-14T00:13:01: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:13:01.351Z'
}
2025-08-14T00:13:43: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:15:22: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:15:25: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:25.732Z'
}
2025-08-14T00:15:26: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:26.820Z'
}
2025-08-14T00:15:28: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:28.903Z'
}
2025-08-14T00:17:28: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:17:33: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:17:48: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:48.652Z'
}
2025-08-14T00:17:49: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:49.728Z'
}
2025-08-14T00:17:51: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:51.801Z'
}
2025-08-14T00:17:51: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:51.929Z'
}
2025-08-14T00:17:52: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:52.999Z'
}
2025-08-14T00:17:55: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:55.082Z'
}
2025-08-14T00:23:18: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:24:22: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:24:26: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:26.191Z'
}
2025-08-14T00:24:27: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:27.266Z'
}
2025-08-14T00:24:29: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:29.349Z'
}
2025-08-14T00:27:24: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:27:31: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:27:56: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:30:06: Error occurred: {
  error: 'Cannot change status while machine is in use or paused',
  stack: 'ValidationError: Cannot change status while machine is in use or paused\n' +
    '    at MachinesService.updateMachineStatus (/home/production-app/production-orders-app/src/services/machines.service.js:167:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:176:28',
  url: '/api/machines/24/status',
  method: 'PATCH',
  user: 'admin',
  timestamp: '2025-08-13T22:30:06.694Z'
}
2025-08-14T00:30:20: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:32:03: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:32:07: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:07: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:07.084Z'
}
2025-08-14T00:32:08: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:08: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:08.153Z'
}
2025-08-14T00:32:10: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:10: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:10.223Z'
}
2025-08-14T00:33:29: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:29: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:29.156Z'
}
2025-08-14T00:33:30: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:30: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:30.242Z'
}
2025-08-14T00:33:32: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:32: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:32.311Z'
}
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:40:00: JWT verification failed: jwt expired
2025-08-14T00:40:02: JWT verification failed: jwt expired
2025-08-14T00:42:15: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T00:45:28: JWT verification failed: jwt malformed
2025-08-14T08:00:15: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:15.708Z'
}
2025-08-14T08:00:16: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:16.761Z'
}
2025-08-14T08:00:18: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:18.807Z'
}
2025-08-14T08:12:13: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T08:12:13: 🔒 Auth failure: admin from ::1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:19: 🔒 Auth failure: admin from ::1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:31: 🔒 Auth failure: Brandon King from ::ffff:127.0.0.1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:43: 🔒 Auth failure: admin from ::1 - Invalid input - curl/8.5.0
2025-08-14T08:50:18: Error occurred: {
  error: 'Cannot update machine while in use',
  stack: 'ValidationError: Cannot update machine while in use\n' +
    '    at MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:128:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/32',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-14T06:50:18.383Z'
}
2025-08-14T08:50:29: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:29.042Z'
}
2025-08-14T08:50:30: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:30.386Z'
}
2025-08-14T08:50:39: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:39.205Z'
}
2025-08-14T08:50:40: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:40.252Z'
}
2025-08-14T08:50:42: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:42.291Z'
}
2025-08-14T08:50:44: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:44.186Z'
}
2025-08-14T08:50:45: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:45.287Z'
}
2025-08-14T08:50:47: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:47.345Z'
}
2025-08-14T08:51:12: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/82/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:51:12.590Z'
}
